[build]
builder = "java-maven"

[phases.setup]
nixPkgs = ["jdk21", "maven"]

[phases.build]
# explicitly cd into where pom.xml is
cmds = [
  "cd server/eq_inventory && mvn clean package -DskipTests"
]

[start]
cmd = "java -jar server/eq_inventory/target/eq-inventory-0.0.1-SNAPSHOT.jar"
