[build]
builder = "java-maven"

[phases.setup]
nixPkgs = ["jdk17", "maven"]

[phases.build]
workingDirectory = "server/eq_inventory"
cmds = [
  "mvn clean package -DskipTests"
]

[start]
cmd = "java -jar server/eq_inventory/target/eq-inventory-0.0.1-SNAPSHOT.jar"
