


[build]
builder = "java-maven"

[phases.setup]
nixPkgs = ["jdk21", "maven"]

[phases.build]
cmds = [
  "cd server/eq_inventory && mvn clean package -DskipTests",
  "cp server/eq_inventory/target/eq-inventory-0.0.1-SNAPSHOT.jar /app/app.jar"
]

[start]
cmd = "java -jar /app/app.jar"
